### ISSUE TITLE
Paypal payment tracking

### ISSUE THREAD

**Issue by KrauseStefan** [KrauseStefan/NavitasFitness#4]
- [x] Locally simulated payments
- [x] User tracking on simulated payments
- [x] Sandbox payments (against paypal sandbox server)

Live payments will be part of the accept test

**Comment by KrauseStefan** [comment]
Payments can now be accepted using the sandbox, they are however not accepted automatically.
Will track this in #10
